//export const SCHEME = 'SCHEME';
//ERROR TYPES
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


//AUTH TYPES
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

//PROFILE TYPES
export const GET_PROFILE = 'GET_PROFILE';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const SEARCH_FOR_MANGA = 'SEARCH_FOR_MANGA';
export const DELETE_MANGA_PROFILE = 'DELETE_MANGA_PROFILE';
export const ADD_MANGA_PROFILE = 'ADD_MANGA_PROFILE';
 
export const CREATE_LIST = 'CREATE_LIST';
export const GET_LISTS = 'GET_LISTS';
export const ADD_LIST_ENTRY = 'ADD_LIST_ENTRY';
export const DEL_LIST_ENTRY = 'DEL_LIST_ENTRY';

//CLEAR
export const CLEAR_MANGA = 'CLEAR_MANGA';
export const CLEAR_LIST = 'CLEAR_LIST';
export const CLEAR_RATING = 'CLEAR_RATING';

//FRIEND REQUESTS
export const GET_FRIEND_REQUESTS = 'GET_FRIEND_REQUESTS';
export const CLEAR_FRIEND_REQUESTS = 'CLEAR_FRIEND_REQUESTS';

//THREAD
export const GET_THREADS = 'GET_THREADS';
export const GET_THREAD = 'GET_THREAD';
export const CLEAR_THREADS = 'CLEAR_THREADS';
export const CLEAR_THREAD = 'CLEAR_THREAD';

//COMMENT
export const GET_COMMENTS = 'GET_COMMENTS';
export const CLEAR_COMMENTS = 'CLEAR_COMMENTS';

//MANGA
export const GET_RATING = 'GET_RATING';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const GET_MANGA = 'GET_MANGA';
export const GET_CHAPTERS = 'GET_CHAPTERS';
export const GET_MANGA_IMAGES = 'GET_MANGA_IMAGES';